# ENG1013 PASS Week 4 - Pokemon Battle Game Config File
# Author: Jonathan Chin and Jamie Lawson
# Updated: 13/03/2026
# Purpose: Contains math configurations for the Pokemon battle game.


############################################
# DO NOT EDIT THIS FILE #
# Please read the README file first for instructions on how to complete the game #
############################################

# Import modules
import random


def generate_attack_answer(attackingPokemon):
    """
    Function to generate the attack question and answer for the attacking Pokemon.
    Inputs: attackingPokemon - index of the attacking Pokemon in the pokemonList
    Outputs: attackQuestion - number of values the user must manipulate
            attackAnswer - answer to the calculation user must guess to successfully attack
    """

    questionSet = random.randint(0,4)

    questionAnswers = [
    [  # Sum of first N prime numbers
        [3, 10],     # 2+3+5
        [4, 17],     # 2+3+5+7
        [5, 28],     # +11
        [6, 41],     # +13
        [7, 58]      # +17
    ],

    [  # Product of first N even numbers
        [2, 8],      # 2*4
        [3, 48],     # 2*4*6
        [4, 384],    # *8
        [5, 3840],   # *10
        [6, 46080]   # *12
    ],

    [  # Sum of first N Fibonacci numbers
        [3, 4],      # 1+1+2
        [4, 7],      # +3
        [5, 12],     # +5
        [6, 20],     # +8
        [7, 33]      # +13
    ],

    [  # Product of first N odd numbers
        [2, 3],      # 1*3
        [3, 15],     # *5
        [4, 105],    # *7
        [5, 945],    # *9
        [6, 10395]   # *1
    ],

    [  # Sum of first N square numbers
        [2, 5],      # 1^2 + 2^2
        [3, 14],     # +9
        [4, 30],     # +16
        [5, 55],     # +25
        [6, 91]      # +36
    ]
]
    return  questionAnswers[attackingPokemon][questionSet][0], questionAnswers[attackingPokemon][questionSet][1]

    
def generate_defend_answer(defendingPokemon):
    """
    Function to generate the defend list and answer for the defending Pokemon.
    Inputs: defendingPokemon - index of the defending Pokemon in the pokemonList
    Outputs: defendQuestion - list of the values the user must manipulate
            defendAnswer - list of values that the user must guess to successfully defend
    """
    
    questionSet = random.randint(0,4)

    questionAnswers = [
    [  # Operation 1: remove every 2nd value
        [[1,2,3,4,5,6], [1,3,5]],
        [[10,20,30,40,50,60], [10,30,50]],
        [[7,8,9,10,11,12], [7,9,11]],
        [[5,15,25,35,45,55], [5,25,45]],
        [[2,4,6,8,10,12], [2,6,10]]
    ],

    [  # Operation 2: remove every 3rd value
        [[1,2,3,4,5,6,7,8,9], [1,2,4,5,7,8]],
        [[10,20,30,40,50,60], [10,20,40,50]],
        [[5,6,7,8,9,10], [5,6,8,9]],
        [[11,12,13,14,15,16], [11,12,14,15]],
        [[2,4,6,8,10,12], [2,4,8,10]]
    ],

    [  # Operation 3: remove every odd value
        [[1,2,3,4,5,6], [2,4,6]],
        [[7,8,9,10,11,12], [8,10,12]],
        [[13,14,15,16], [14,16]],
        [[21,22,23,24,25], [22,24]],
        [[3,6,9,12], [6,12]]
    ],

    [  # Operation 4: remove every even value
        [[1,2,3,4,5,6], [1,3,5]],
        [[10,11,12,13,14], [11,13]],
        [[7,8,9,10], [7,9]],
        [[20,21,22,23], [21,23]],
        [[2,3,4,5,6,7], [3,5,7]]
    ],

    [  # Operation 5: remove values greater than 10
        [[5,8,12,3,15], [5,8,3]],
        [[2,11,4,9,13], [2,4,9]],
        [[10,14,7,18], [10,7]],
        [[1,20,2,30,3], [1,2,3]],
        [[6,7,8,11,12], [6,7,8]]
    ]
]

    return questionAnswers[defendingPokemon][questionSet][0], questionAnswers[defendingPokemon][questionSet][1]