
# ENG1013 PASS Week 4 - Pokemon Battle Game
# Author: Jonathan Chin and Jamie Lawson
# Updated: 13/03/2026
# Purpose: Main game engine file for the Pokemon battle game.
#          This sets up the battle, gets player input, and runs the main game loop where players take turns attacking and defending until only one Pokemon remains.


############################################
# DO NOT EDIT THIS FILE #
# Please read the README file first for instructions on how to complete the game #
############################################



# Import modules
import random
import time
import config
from Pokemon.pikachu import pikachu_attack, pikachu_defend
from Pokemon.bulbasaur import bulbasaur_attack, bulbasaur_defend
from Pokemon.charmander import charmander_attack, charmander_defend
from Pokemon.squirtle import squirtle_attack, squirtle_defend
from Pokemon.mewtwo import mewtwo_attack, mewtwo_defend


# Setting up battle
print("\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("\n\nWelcome to the Pokemon battle game!")
time.sleep(0.75)

# Getting player count
while True:

    # Validate user input for number of players
    try:
        # Ask user for number of players
        numPlayers = input("\n\nPlease enter number of players: ")
        time.sleep(0.3)

        # Check if input is a valid number between 2 and 5
        if int(numPlayers) < 2 or int(numPlayers) > 5:
            print("Invalid number of players. Please enter a number between 2 and 5.")
            continue

    except ValueError:
        print("Invalid input. Please enter a number.")
        continue

    break
time.sleep(0.5)


# Print number of players
print("You have entered " + numPlayers + " players.\n\n")
time.sleep(0.5)

# Setting up pokemon and game variables
pokemonStats = {
    "name": "",
    "health": 0
}
pokemonNames = ["Pikachu", "Bulbasaur", "Charmander", "Squirtle", "Mewtwo"]
pokemonList = []

# Creating each players Pokemon
for i in range(int(numPlayers)):
    pokemonList.append(pokemonStats.copy())
    pokemonList[i]["name"] = pokemonNames[i]
    pokemonList[i]["health"] = 100
    print("Player " + str(i + 1) + " has chosen " + pokemonList[i]["name"])
    time.sleep(0.5)


# Starting battle
input("\nPress Enter to continue...\n")
print("\n\n\nLet the battle begin!")
time.sleep(1)
print("Each player will take turns randomly attacking each other until the last Pokemon remains.")
time.sleep(1)
print("\nGood luck!!\n")
time.sleep(1)




def main():
    """
    Main function to run the Pokemon battle game.
    Inputs: None
    Outputs: None
    """

    roundCounter = 1

    # Main game loop
    while True:

        # Print round number
        time.sleep(1)
        input("\nPress Enter to continue...\n")
        print("\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        print("\n\n~~~ Round " + str(roundCounter) + "! ~~~\n")

        # Check for alive Pokemon and print health
        validPokemon = []
        for i in range(len(pokemonList)):
            time.sleep(0.5)
            if pokemonList[i]["health"] > 0:
                print(pokemonList[i]["name"] + " has " + str(pokemonList[i]["health"]) + " health remaining.")
                validPokemon.append(i)
            else:
                print(pokemonList[i]["name"] + " has fainted!")

        time.sleep(1)
        input("\nPress Enter to continue...\n")
        
        # One Pokemon remaining, end game
        if len(validPokemon) == 1:
            time.sleep(1)
            print(f'{pokemonList[validPokemon[0]]["name"]} is the last Pokemon standing and wins the battle!\n')
            break


        # Picking a random attacking Pokemon
        attackingPokemon = random.choice(validPokemon)
        validPokemon.remove(attackingPokemon)

        # Picking a random defending Pokemon
        defendingPokemon = random.choice(validPokemon)
        validPokemon.remove(defendingPokemon)

        # Announce attack
        print(f'\n~~~~~~~~~~~~~~~\n{pokemonList[attackingPokemon]["name"]} is attacking {pokemonList[defendingPokemon]["name"]}!\n')
        time.sleep(1.5)


        # Generate attack guess and answer
        attackQuestion, attackAnswer = config.generate_attack_answer(attackingPokemon)
        defendQuestion, defendAnswer = config.generate_defend_answer(defendingPokemon)


        # Run the attack functions for the attacking Pokemon
        if attackingPokemon == 0:
            attackGuess = pikachu_attack(attackQuestion)
        elif attackingPokemon == 1:
            attackGuess = bulbasaur_attack(attackQuestion)
        elif attackingPokemon == 2:
            attackGuess = charmander_attack(attackQuestion)
        elif attackingPokemon == 3:
            attackGuess = squirtle_attack(attackQuestion)
        elif attackingPokemon == 4:
            attackGuess = mewtwo_attack(attackQuestion)

        
        # Run the defend functions for the defending Pokemon
        if defendingPokemon == 0:
            defendGuess = pikachu_defend(defendQuestion)
        elif defendingPokemon == 1:
            defendGuess = bulbasaur_defend(defendQuestion)
        elif defendingPokemon == 2:
            defendGuess = charmander_defend(defendQuestion)
        elif defendingPokemon == 3:
            defendGuess = squirtle_defend(defendQuestion)
        elif defendingPokemon == 4:
            defendGuess = mewtwo_defend(defendQuestion)


        # Check if attack was successful
        if attackGuess == attackAnswer:
            print(pokemonList[attackingPokemon]["name"] + "'s attack was successful!")
            attack = random.randint(50, 100)
        else:
            print(pokemonList[attackingPokemon]["name"] + "'s attack was unsuccessful!")
            attack = 0
        time.sleep(1)

        # Check if defend was successful
        if defendGuess == defendAnswer:
            print(pokemonList[defendingPokemon]["name"] + " successfully defended the attack!")
            defend = True
        else:
            print(pokemonList[defendingPokemon]["name"] + " failed to defend the attack!")
            defend = False

        time.sleep(1)

        # Calculate damage and update health
        if defend:
            attack = attack // 2
        pokemonList[defendingPokemon]["health"] -= attack
        print("\n" + pokemonList[attackingPokemon]["name"] + " dealt " + str(attack) + " damage to " + pokemonList[defendingPokemon]["name"] + "!")

        # Increment round counter
        roundCounter += 1



# Run the main function        
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nGame interrupted. Exiting...\n")
    print("\n\nThank you for playing the Pokemon battle game! We hope you had fun and learned something new!\n\n")
